//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT028863:"Business Vertical portfolio income expense report",FLT028864:"SOL/SET ID",FLT012932:"Scheme code",FLT028865:"As on date",FLT000193:"Submit",FLT000194:"Validate",FLT000192:"Cancel",FLT003170:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
